version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    ports:
      - "3000:3000" 
    command: npm run start
